runtime! archlinux.vim

set nocompatible

autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
au InsertLeave * match ExtraWhitespace /\s\+$/

set t_Co=256
color wombat256mod

" Enable syntax highlighting
filetype off
filetype plugin indent on
syntax on

" Automaticlly indent when adding a curly barket, ...
set smartindent

" Showing line numbers and length
set number  " show line numbers
set tw=79   " width of document (used by gd)
set nowrap  " don't automatically wrap on load
set fo-=t   " don't automatically wrap text when typing
set colorcolumn=80
highlight ColorColumn ctermbg=233

" Make search case insensitive
set hlsearch
set incsearch
set ignorecase
set smartcase

set nobackup
set nowritebackup
set noswapfile

" Settings for powerline (AUR:python-powerline-git)
" git://github.com/Lokaltog/powerline.git
let g:Powerline_symbols = 'unicode'
set laststatus=2

" use UTF-8 encoding
set encoding=utf-8

" show line number, cursor position
set ruler

" show incomplete commands
set showcmd
