" uncommon settings
" set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
set nocompatible
"autocmd! bufwritepost .vimrc source %
set ttyfast
set encoding=utf-8   " use UTF-8 encoding

set backupdir=$XDG_CACHE_HOME/vim-backup
set viminfo+=n$XDG_CACHE_HOME/viminfo

"set backup
"set backupext   =-vimbackup
"set backupskip  =
"set directory   =$HOME/.vim/files/swap//
"set updatecount =100
"set undofile
set undodir  =$XDG_CACHE_HOME/vim-undo
set directory=$XDG_CACHE_HOME/vim-swap

" vundle
source $XDG_CONFIG_HOME/vim/vundle.vim

" common settings
source $XDG_CONFIG_HOME/vim/common.vim
